server:
  port: 18082
spring:
  cloud:
#    nacos
    nacos:
      discovery:
        server-addr: localhost:8848
#   sentinel
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
#   zipkin
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: true
    sender:
      type: web
  #  sleuth ???
  sleuth:
    sampler:
      probability: 1
# ???
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.128:3306/guli_sms
    username: root
    password: onceas
#  redis
  redis:
    host: 192.168.2.128
    port: 6379
# feign
feign:
  sentinel:
    enabled: true
# mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/sms/**/*.xml
  global-config:
    db-config:
      id-type: auto
#  别名扫描
  type-aliases-package: com.jie.gmall.sms.entity

